### ISSUE TITLE
Release Workflow Fails When No Commits Exist Between Branches

### ISSUE THREAD

**Issue by galligan** [galligan/grepa#35]
## Summary:

The release workflow fails with the following error when there are no new commits between `main` and `changeset-release/main`:
```
Validation Failed: {"resource":"PullRequest","code":"custom","message":"No commits between main and changeset-release/main"}
```

### Where

Release workflow: [.github/workflows/release.yml@ec38ad1](https://github.com/galligan/grepa/blob/ec38ad10673597324629f307ba592c2bd299ff73/.github/workflows/release.yml)  
Example job log: [Failed job log](https://github.com/galligan/grepa/actions/runs/15355680146/job/43214089473)

### Details

- The workflow attempts to create a release PR even when there are no new commits.
- This results in a validation failure from the GitHub API.

## Proposed Solution

Add a step to check for changes between `main` and `changeset-release/main` before attempting to create a release PR. Skip the PR creation step if there are no changes.

### Suggested Workflow Update

```yaml
- name: Check for changes between main and changeset-release/main
  id: check_changes
  run: |
    git fetch origin main:main
    if git diff --quiet origin/main; then
      echo "no-changes=true" >> $GITHUB_ENV
    else
      echo "no-changes=false" >> $GITHUB_ENV
    fi

- name: Create Release Pull Request or Publish
  if: env.no-changes == 'false'
  uses: changesets/action@v1
  # ... (rest of your step config)
```
