### ISSUE TITLE
Release Workflow Fails When No Changes Are Detected

### ISSUE THREAD

**Issue by galligan** [galligan/grepa#40]
**Description**
The failing job indicates that the release workflow attempted to create a pull request, but there were no changes detected between the `main` branch and the `changeset-release/main` branch. This is due to a validation error:

> “No commits between main and changeset-release/main.”

---

### Problem Analysis
The failure originates from the step responsible for checking for changes between the `main` branch and the `changeset-release/main` branch. Specifically:
- If no differences are detected, the workflow still attempts to execute the release process, which fails because there are no commits to release.

---

### Solution
To resolve this issue, ensure that the workflow skips the release process if no changes are detected. The logic already marks the `has_changes` output in the **Check for changes** step. However, the condition for the **Create Release Pull Request or Publish** step is incorrect or not strict enough.

---

### Suggested Fix
Update the condition for the **Create Release Pull Request or Publish** step to ensure it only runs when changes are detected. Modify the `if` condition from:

```yaml
if: steps.check_changes.outputs.has_changes == 'true'
```

to:

```yaml
if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
```

---

### Updated Workflow Code
Here’s the corrected part of the workflow:

```yaml
- name: Create Release Pull Request or Publish
  if: ${{ steps.check_changes.outputs.has_changes == 'true' }}
  id: changesets
  uses: changesets/action@v1
  with:
    publish: pnpm release
    version: pnpm version
    commit: "chore: version packages"
    title: "chore: version packages"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

---

### Additional Suggestions
1. **Improve Logging**:  
   Add more detailed logs in the **Check for changes** step to help debug similar issues in the future. For example, print out which commits (if any) were compared or a message indicating that no changes were found.

2. **Pre-Validation**:  
   Consider a pre-validation step that explicitly checks for changes before triggering the entire release workflow. This can prevent wasted workflow runs and reduce noise.

---

### Reference
You can view the full workflow file [here](https://github.com/galligan/grepa/blob/7f71c1592e3a609514b9d7dd3717bb20a58b9f00/.github/workflows/release.yml).
